export const team = [
    {
      name: "Vann Vat",
      role: "Team Leader & Data Engineer",
      bio: "Passionate leader with expertise in data engineering and project management. Dedicated to building accessible technology that bridges communication gaps in the deaf community.",
      socials: {
        twitter: "#",
        linkedin: "#",
        github: "#",
        discord: "#",
        email: "vannvat@example.com",
        telegram: "#",
        facebook: "#",
      },
    },
    {
      name: "Chim Panhaprasith",
      role: "Frontend Developer",
      bio: "Creative frontend developer focused on building intuitive and accessible user interfaces. Committed to creating seamless user experiences that make technology available to everyone.",
      socials: {
        twitter: "#",
        linkedin: "#",
        github: "#",
        discord: "#",
        email: "panhaprasith@example.com",
        telegram: "https://t.me/panhaprasith",
        facebook: "#",
      },
    },
    {
      name: "Chhi Hangcheav",
      role: "Backend Developer",
      bio: "Backend specialist with strong skills in API development and system architecture. Focused on building robust and scalable solutions for real-time communication systems.",
      socials: {
        twitter: "#",
        linkedin: "#",
        github: "#",
        discord: "#",
        email: "hangcheav@example.com",
        telegram: "#",
        facebook: "#",
      },
    },
    {
      name: "Toek Hengsreng",
      role: "Dataset & Research Analyst",
      bio: "Machine learning enthusiast with a focus on model training and optimization. Passionate about applying AI to solve real-world problems and improve accessibility through technology.",
      socials: {
        twitter: "#",
        linkedin: "#",
        github: "#",
        discord: "#",
        email: "hengsreng@example.com",
        telegram: "#",
        facebook: "#",
      },
    },
    {
      name: "Mony Meakputsoktheara",
      role: "Machine Learning Engineer",
      bio: "Skilled ML engineer specializing in computer vision and gesture recognition. Driven to develop intelligent systems that can understand and translate human movements.",
      socials: {
        twitter: "#",
        linkedin: "#",
        github: "#",
        discord: "#",
        email: "meakputsoktheara@example.com",
        telegram: "https://t.me/araeht",
        facebook: "#",
      },
    },
    {
      name: "Phal Sovandy",
      role: "UI/UX Designer & Content Lead",
      bio: "Creative designer passionate about user-centered design and accessibility. Dedicated to crafting beautiful interfaces that are inclusive and easy to use for everyone.",
      socials: {
        twitter: "https://x.com/sovandy_phal",
        linkedin: "https://www.linkedin.com/in/sovandy-phal-382069331/",
        github: "https://github.com/Phal-Sovandy",
        discord: "https://discordapp.com/users/696681524161937519",
        email: "phalsovandy007@gmail.com",
        telegram: "https://t.me/l_Brilliant_l",
        facebook: "https://www.facebook.com/kallMeDy/",
      },
    },
  ];